"use client";

import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { createClient } from "@/lib/supabase/client";

// Upload a Claude-generated HTML file, preview it, and create a project.
export default function UploadPage() {
  const router = useRouter();
  const fileRef = useRef<HTMLInputElement>(null);
  const [html, setHtml] = useState("");
  const [name, setName] = useState("");
  const [size, setSize] = useState(0);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [dragging, setDragging] = useState(false);

  function readFile(file: File) {
    if (!/\.html?$/i.test(file.name)) {
      setError("Please choose an .html file.");
      return;
    }
    setError("");
    setSize(file.size);
    const reader = new FileReader();
    reader.onload = () => {
      setHtml(String(reader.result ?? ""));
      setName(file.name.replace(/\.html?$/i, ""));
    };
    reader.readAsText(file);
  }

  async function create() {
    setBusy(true);
    setError("");
    const supabase = createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();
    if (!user) return router.push("/login");

    const { data: project, error: pErr } = await supabase
      .from("projects")
      .insert({ owner_id: user.id, name: name || "Untitled project" })
      .select("id")
      .single();
    if (pErr || !project) {
      setBusy(false);
      return setError(pErr?.message ?? "Could not create project");
    }

    const { data: doc, error: dErr } = await supabase
      .from("documents")
      .insert({
        project_id: project.id,
        title: name || "Untitled document",
        html_content: html,
        updated_by: user.id,
      })
      .select("id")
      .single();
    if (dErr || !doc) {
      setBusy(false);
      return setError(dErr?.message ?? "Could not create document");
    }

    await supabase.from("document_versions").insert({
      document_id: doc.id,
      html_content: html,
      label: "Initial upload",
      created_by: user.id,
    });
    await supabase.from("activity_log").insert({
      project_id: project.id,
      user_id: user.id,
      action: "uploaded",
      details: { title: name },
    });

    router.push(`/editor/${doc.id}`);
  }

  return (
    <main className="min-h-screen bg-slate-50">
      <div className="max-w-3xl mx-auto px-6 py-10">
        <Link href="/dashboard" className="text-sm text-slate-400 hover:text-slate-900 transition-colors">
          ← Back to dashboard
        </Link>
        <h1 className="mt-4 text-2xl font-bold tracking-tight text-slate-900">
          Upload an HTML report or presentation
        </h1>
        <p className="mt-1.5 text-slate-500 text-sm">
          Drop in a file generated by Claude. You&apos;ll edit it visually — the original
          design is never modified, so charts and scripts keep working.
        </p>

        {!html ? (
          <div
            className={`mt-8 rounded-2xl border-2 border-dashed p-16 text-center cursor-pointer transition-all ${
              dragging
                ? "border-indigo-500 bg-indigo-50 scale-[1.01]"
                : "border-slate-300 bg-white hover:border-indigo-400"
            }`}
            onClick={() => fileRef.current?.click()}
            onDragOver={(e) => { e.preventDefault(); setDragging(true); }}
            onDragLeave={() => setDragging(false)}
            onDrop={(e) => {
              e.preventDefault();
              setDragging(false);
              const f = e.dataTransfer.files?.[0];
              if (f) readFile(f);
            }}
          >
            <div className="mx-auto h-14 w-14 rounded-2xl bg-indigo-50 flex items-center justify-center text-2xl">📄</div>
            <p className="mt-4 font-semibold text-slate-700">Click to choose a file or drag it here</p>
            <p className="mt-1 text-sm text-slate-400">.html or .htm — any size</p>
            <input
              ref={fileRef}
              type="file"
              accept=".html,.htm,text/html"
              className="hidden"
              onChange={(e) => {
                const f = e.target.files?.[0];
                if (f) readFile(f);
              }}
            />
          </div>
        ) : (
          <div className="mt-8 space-y-4">
            <div className="card p-5 space-y-4">
              <div>
                <label className="label">Project name</label>
                <input className="input" value={name} onChange={(e) => setName(e.target.value)} />
              </div>
              <div>
                <div className="flex items-center justify-between mb-1">
                  <label className="label !mb-0">Preview</label>
                  <span className="text-[11px] text-slate-400">{(size / 1024).toFixed(0)} KB</span>
                </div>
                {/* Sandboxed: uploaded scripts run in an opaque origin, isolated from the app */}
                <iframe
                  sandbox="allow-scripts"
                  srcDoc={html}
                  className="w-full h-96 rounded-xl border border-slate-200 bg-white"
                  title="Upload preview"
                />
              </div>
            </div>
            <div className="flex gap-3">
              <button className="btn-primary" onClick={create} disabled={busy}>
                {busy ? "Creating…" : "Create project & open editor"}
              </button>
              <button className="btn-ghost" onClick={() => { setHtml(""); setName(""); }}>
                Choose another file
              </button>
            </div>
          </div>
        )}
        {error && <p className="mt-4 text-sm text-red-600">{error}</p>}
      </div>
    </main>
  );
}
