"use client";

import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { createClient } from "@/lib/supabase/client";

// Upload a Claude-generated HTML file, preview it, and create a project.
export default function UploadPage() {
  const router = useRouter();
  const fileRef = useRef<HTMLInputElement>(null);
  const [html, setHtml] = useState("");
  const [name, setName] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [dragging, setDragging] = useState(false);

  function readFile(file: File) {
    if (!/\.html?$/i.test(file.name)) {
      setError("Please choose an .html file.");
      return;
    }
    setError("");
    const reader = new FileReader();
    reader.onload = () => {
      setHtml(String(reader.result ?? ""));
      setName(file.name.replace(/\.html?$/i, ""));
    };
    reader.readAsText(file);
  }

  async function create() {
    setBusy(true);
    setError("");
    const supabase = createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();
    if (!user) return router.push("/login");

    // 1. project
    const { data: project, error: pErr } = await supabase
      .from("projects")
      .insert({ owner_id: user.id, name: name || "Untitled project" })
      .select("id")
      .single();
    if (pErr || !project) {
      setBusy(false);
      return setError(pErr?.message ?? "Could not create project");
    }

    // 2. document
    const { data: doc, error: dErr } = await supabase
      .from("documents")
      .insert({
        project_id: project.id,
        title: name || "Untitled document",
        html_content: html,
        updated_by: user.id,
      })
      .select("id")
      .single();
    if (dErr || !doc) {
      setBusy(false);
      return setError(dErr?.message ?? "Could not create document");
    }

    // 3. initial version + activity
    await supabase.from("document_versions").insert({
      document_id: doc.id,
      html_content: html,
      label: "Initial upload",
      created_by: user.id,
    });
    await supabase.from("activity_log").insert({
      project_id: project.id,
      user_id: user.id,
      action: "uploaded",
      details: { title: name },
    });

    router.push(`/editor/${doc.id}`);
  }

  return (
    <main className="min-h-screen max-w-3xl mx-auto px-6 py-10">
      <Link href="/dashboard" className="text-sm text-gray-500 hover:text-gray-900">← Back to dashboard</Link>
      <h1 className="mt-4 text-2xl font-bold">Upload an HTML report or presentation</h1>
      <p className="mt-1 text-gray-500 text-sm">
        Drop in a file generated by Claude. You&apos;ll be able to edit it visually — the
        original design is preserved.
      </p>

      {!html ? (
        <div
          className={`mt-8 rounded-xl border-2 border-dashed p-16 text-center cursor-pointer transition-colors ${
            dragging ? "border-brand-500 bg-brand-50" : "border-gray-300 hover:border-brand-500"
          }`}
          onClick={() => fileRef.current?.click()}
          onDragOver={(e) => { e.preventDefault(); setDragging(true); }}
          onDragLeave={() => setDragging(false)}
          onDrop={(e) => {
            e.preventDefault();
            setDragging(false);
            const f = e.dataTransfer.files?.[0];
            if (f) readFile(f);
          }}
        >
          <p className="text-4xl">📄</p>
          <p className="mt-3 font-medium">Click to choose a file or drag it here</p>
          <p className="mt-1 text-sm text-gray-400">.html or .htm</p>
          <input
            ref={fileRef}
            type="file"
            accept=".html,.htm,text/html"
            className="hidden"
            onChange={(e) => {
              const f = e.target.files?.[0];
              if (f) readFile(f);
            }}
          />
        </div>
      ) : (
        <div className="mt-8 space-y-4">
          <div>
            <label className="label">Project name</label>
            <input className="input" value={name} onChange={(e) => setName(e.target.value)} />
          </div>
          <div>
            <label className="label">Preview</label>
            {/* Sandboxed: uploaded scripts run in an opaque origin, isolated from the app */}
            <iframe
              sandbox="allow-scripts"
              srcDoc={html}
              className="w-full h-96 rounded-xl border border-gray-200 bg-white"
              title="Upload preview"
            />
          </div>
          <div className="flex gap-3">
            <button className="btn-primary" onClick={create} disabled={busy}>
              {busy ? "Creating…" : "Create project & open editor"}
            </button>
            <button className="btn-ghost" onClick={() => { setHtml(""); setName(""); }}>
              Choose another file
            </button>
          </div>
        </div>
      )}
      {error && <p className="mt-4 text-sm text-red-600">{error}</p>}
    </main>
  );
}
