import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "ReportCanvas — Visual editor for HTML reports & presentations",
  description:
    "Upload HTML reports and presentations generated by Claude, edit them visually, collaborate in real time, and export.",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-900 antialiased">{children}</body>
    </html>
  );
}
