import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import SignOutButton from "@/components/SignOutButton";
import ProjectCard, { type ProjectCardData } from "@/components/dashboard/ProjectCard";
import DemoButton from "@/components/dashboard/DemoButton";
import { initials, userColor } from "@/lib/colors";

export const dynamic = "force-dynamic";

interface Membership {
  role: string;
  projects: {
    id: string;
    name: string;
    owner_id: string;
    updated_at: string;
    documents: { id: string; title: string; updated_at: string }[];
  } | null;
}

export default async function Dashboard() {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return null; // middleware redirects

  const { data: profile } = await supabase
    .from("profiles")
    .select("full_name, email")
    .eq("id", user.id)
    .single();

  const { data } = await supabase
    .from("project_members")
    .select("role, projects(id, name, owner_id, updated_at, documents(id, title, updated_at))")
    .eq("user_id", user.id);

  const memberships = ((data as unknown as Membership[]) ?? []).filter((m) => m.projects);
  const toCard = (m: Membership): ProjectCardData => {
    const p = m.projects!;
    const doc = p.documents?.[0];
    return {
      projectId: p.id,
      docId: doc?.id ?? null,
      name: p.name,
      docTitle: doc?.title ?? "No document",
      role: m.role,
      updatedAt: doc?.updated_at ?? null,
      isOwner: p.owner_id === user.id,
    };
  };
  const sortByDate = (a: ProjectCardData, b: ProjectCardData) =>
    (b.updatedAt ?? "").localeCompare(a.updatedAt ?? "");
  const mine = memberships.filter((m) => m.projects!.owner_id === user.id).map(toCard).sort(sortByDate);
  const shared = memberships.filter((m) => m.projects!.owner_id !== user.id).map(toCard).sort(sortByDate);

  const name = profile?.full_name || profile?.email || "You";

  return (
    <main className="min-h-screen bg-slate-50">
      <header className="border-b border-slate-200 bg-white/85 backdrop-blur sticky top-0 z-10">
        <div className="max-w-6xl mx-auto px-6 py-3.5 flex items-center justify-between">
          <Link href="/dashboard" className="flex items-center gap-2.5 font-bold tracking-tight">
            <span className="logo-chip">▦</span>
            ReportCanvas
          </Link>
          <div className="flex items-center gap-3">
            <div className="flex items-center gap-2">
              <span
                className="flex h-8 w-8 items-center justify-center rounded-full text-xs font-bold text-white"
                style={{ backgroundColor: userColor(user.id) }}
                title={name}
              >
                {initials(profile?.full_name ?? "", profile?.email ?? "")}
              </span>
              <span className="text-sm text-slate-600 hidden sm:block">{name}</span>
            </div>
            <SignOutButton />
          </div>
        </div>
      </header>

      {/* gradient hero band */}
      <div className="bg-gradient-to-r from-violet-600 via-fuchsia-600 to-amber-500">
        <div className="max-w-6xl mx-auto px-6 py-8 flex flex-wrap items-center justify-between gap-3">
          <div className="animate-fade-up">
            <h1 className="text-2xl font-extrabold tracking-tight text-white">
              Welcome back{profile?.full_name ? `, ${profile.full_name.split(" ")[0]}` : ""} 👋
            </h1>
            <p className="text-sm text-white/80 mt-0.5">
              {mine.length} project{mine.length === 1 ? "" : "s"}
              {shared.length > 0 && ` · ${shared.length} shared with you`}
            </p>
          </div>
          <div className="flex gap-2 animate-fade-up [animation-delay:100ms]">
            <DemoButton />
            <Link
              href="/upload"
              className="inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2 text-sm font-bold text-fuchsia-700 shadow-lg hover:scale-[1.03] active:scale-100 transition-transform"
            >
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"><path d="M12 5v14M5 12h14" /></svg>
              Upload HTML
            </Link>
          </div>
        </div>
      </div>

      <div className="max-w-6xl mx-auto px-6 py-8">
        {mine.length === 0 && shared.length === 0 ? (
          <div className="mt-2 card border-2 border-dashed !border-violet-200 !shadow-none p-14 text-center bg-transparent animate-fade-up">
            <p className="text-4xl">📄</p>
            <h2 className="mt-4 font-semibold text-slate-700">No projects yet</h2>
            <p className="mt-1 text-sm text-slate-400 max-w-sm mx-auto">
              Upload an HTML report generated by Claude, or try the built-in sample to
              see how the editor works.
            </p>
            <div className="mt-6 flex justify-center gap-3">
              <DemoButton />
              <Link href="/upload" className="btn-primary">Upload your first report</Link>
            </div>
          </div>
        ) : (
          <>
            <h2 className="text-lg font-bold text-slate-900">Your projects</h2>
            <div className="mt-4 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
              {mine.map((p, i) => (
                <div key={p.projectId} className="animate-fade-up" style={{ animationDelay: `${i * 60}ms` }}>
                  <ProjectCard p={p} />
                </div>
              ))}
            </div>
          </>
        )}

        {shared.length > 0 && (
          <>
            <h2 className="mt-12 text-lg font-bold text-slate-900">Shared with you</h2>
            <div className="mt-4 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
              {shared.map((p, i) => (
                <div key={p.projectId} className="animate-fade-up" style={{ animationDelay: `${i * 60}ms` }}>
                  <ProjectCard p={p} />
                </div>
              ))}
            </div>
          </>
        )}
      </div>
    </main>
  );
}
